//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leader
    {
        public int LID { get; set; }
        public string LName { get; set; }
        public string LPhone { get; set; }
        public string LEmail { get; set; }
        public string LDivisionCode { get; set; }
    }
}
