//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleLife
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EagleLifeDBEntities : DbContext
    {
        public EagleLifeDBEntities()
            : base("name=EagleLifeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Leader> Leaders { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SmallGroup> SmallGroups { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<TeenMom> TeenMoms { get; set; }
    }
}
