//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeenMom
    {
        public int TID { get; set; }
        public string TName { get; set; }
        public string TPhone { get; set; }
        public string TSchool { get; set; }
        public Nullable<int> TDivisionCode { get; set; }
    
        public virtual Division Division { get; set; }
    }
}
